# - hosts: DockerDB
#   vars_files:
#     - host_vars/couchdb.yaml
#   gather_facts: true
#   vars:
#     - ansible_user: ubuntu
#     - ansible_ssh_private_key_file: ~/.ssh/CCC-T43-A2
#     - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#   roles:
#     # - role: clone_gitrepo
#     # - role: git-pull

# ---
# - hosts: instance3-data
#   vars_files:
#     - host_vars/couchdb.yaml
#   gather_facts: true
#   vars:
#     - ansible_user: ubuntu
#     - ansible_ssh_private_key_file: ~/.ssh/CCC-T43-A2
#     - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#   roles:
#     - role: twitter-crawler 

- hosts: instance2-backend
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/CCC-T43-A2
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: git-pull
    - role: backend