---
- hosts: instance2-backend # on backend instance run twitter crawler
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/CCC-T43-A2
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: git-pull # make sure instance have the latest code version
    - role: twitter-crawler-demo 
