---
# stop and delete the couchDB cont
- name: Stop and delete currunt couchDB cont
  become: yes
  docker_container:
    name: couchdb
    state: absent

# create and start a new cont for couchDB
- name: Create and start run a cont for couchDB
  become: yes
  docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ CouchDBVERSION }}"
    state: started
    recreate: true
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    pull: yes
    env:
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""
