# Common variables
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999 # ubuntu 20.04
instance_key_name: CCC-T43-A2  # ssh key
instance_flavor: uom.mse.2c9g # use the 2 cores 9 gb flavor
project_working_directory: /Users/xavier/Desktop/CCC/Assignment2/CCC2022S1A2-group43/Ansible_Deployment/inventory/hosts.ini

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-2
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-3
    vol_size: 150
    device: /dev/vdb
    mountpoint: /data
  - vol_name: vol-4
    vol_size: 150
    device: /dev/vdb
    mountpoint: /data

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  
  - name: http
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: https
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0 

# Instance
instances:
  - name: instance1-frontend
    security_groups: ['ssh']
    volumes: ['vol-1']
  - name: instance2-backend
    security_groups: ['ssh','http','https']
    volumes: ['vol-2']
  - name: instance3-data
    security_groups: ['ssh']
    volumes: ['vol-3']
  - name: instance4-analysis
    security_groups: ['ssh']
    volumes: [ 'vol-4' ]  
    
# Proxy
proxy_env:
  no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au
  HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  http_proxy: http://wwwproxy.unimelb.edu.au:8000/
  https_proxy: http://wwwproxy.unimelb.edu.au:8000/
