---
# Build Docker image for backend
- name: use Dockerfile to build image
  docker_image:
    build:
      path: '/home/ubuntu/CCCA2/CCC2022S1A2-group43/backend_b/'
      pull: yes
    name: backend-docker
    tag: latest
    source: build
  become: yes
  environment: "{{ proxy_env }}"

  # Create new docker container for Backend and start container
- name: create and start the docker for backend
  become: yes
  docker_container:
    name: backend
    image: backend-docker
    state: started
    pull: false
    recreate: true