---
# copy GitHUB ssh key to ubuntu
- name: copy GitHub Key to instance
  ansible.builtin.copy:
    src: "configure/keyGit"
    dest: /home/ubuntu/.ssh/keyGit
    owner: ubuntu
    group: ubuntu
    backup: no
    decrypt: yes
    force: yes
    mode: 0600

# add GitHub private key
- name: add GitHub key to instance
  template:
    src: "configure/configure_ssh"
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: 0644

# creating directory
- name: Creates CCCA2 directory
  ansible.builtin.file:
    path: '{{ mrc_workdir }}'
    state: directory
    force: no

# start clone from GitHub
- name: pull clone
  ansible.builtin.shell: 
    git clone git@github.com:Zhuo-Yuanhao/CCC2022S1A2-group43.git --config core.sshCommand="ssh -i /home/ubuntu/.ssh/keyGit"
  args:
    chdir: '{{ mrc_workdir }}'
  environment: "{{ proxy_env }}"
  