---
# install dependencies on the host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip'] # sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
# pip install --upgrade pip && pip install openstacksdk
- name: Update pip
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest



